export default {
    "data": {
        "@num": "932-71440272",
        "awbOrigin": "LHR",
        "awbDestination": "MIA",
        "awbPieces": "1",
        "awbWeight": "134.0",
        "awbVolume": "0.62",
        "routing": "",
        "segments": [
            {
                "@sequence": "1",
                "origin": "LHR",
                "dest": "MIA",
                "flightNum": "VS005",
                "flightCat": "P",
                "flightDate": "15SEP22",
                "arrivalDate": "15SEP22",
                "arrivalTime": "18:01",
                "numPieces": "1",
                "weight": "134.0",
                "volume": "0.0",
                "status": "Arrival documents delivered to Consignee/Agent",
                "eventDate": "15SEP22",
                "eventTime": "18:25",
                "statusCode": "AWD"
            },
            {
                "@sequence": "2",
                "origin": "LHR",
                "dest": "MIA",
                "flightNum": "VS005",
                "flightCat": "P",
                "flightDate": "15SEP22",
                "arrivalDate": "15SEP22",
                "arrivalTime": "18:01",
                "numPieces": "1",
                "weight": "134.0",
                "volume": "0.62",
                "status": "Arrived",
                "eventDate": "15SEP22",
                "eventTime": "19:48",
                "statusCode": "ARR"
            },
            {
                "@sequence": "3",
                "origin": "LHR",
                "dest": "MIA",
                "flightNum": "VS005",
                "flightCat": "P",
                "flightDate": "15SEP22",
                "arrivalDate": "15SEP22",
                "arrivalTime": "18:01",
                "numPieces": "1",
                "weight": "134.0",
                "volume": "0.62",
                "status": "Received From Flight",
                "eventDate": "15SEP22",
                "eventTime": "19:48",
                "statusCode": "RCF"
            },
            {
                "@sequence": "4",
                "origin": "LHR",
                "dest": "MIA",
                "flightNum": "VS005",
                "flightCat": "P",
                "flightDate": "15SEP22",
                "arrivalDate": "15SEP22",
                "arrivalTime": "18:01",
                "numPieces": "1",
                "weight": "134.0",
                "volume": "0.0",
                "status": "Arrived",
                "eventDate": "15SEP22",
                "eventTime": "16:37",
                "statusCode": "ARR"
            },
            {
                "@sequence": "5",
                "origin": "LHR",
                "dest": "MIA",
                "flightNum": "VS005",
                "flightCat": "P",
                "flightDate": "15SEP22",
                "arrivalDate": "15SEP22",
                "arrivalTime": "18:01",
                "numPieces": "1",
                "weight": "134.0",
                "volume": "0.0",
                "status": "Consignee/Agent notified of arrival",
                "eventDate": "15SEP22",
                "eventTime": "20:37",
                "statusCode": "NFD"
            },
            {
                "@sequence": "6",
                "origin": "LHR",
                "dest": "MIA",
                "flightNum": "VS005",
                "flightCat": "P",
                "flightDate": "15SEP22",
                "arrivalDate": "15SEP22",
                "arrivalTime": "18:01",
                "numPieces": "1",
                "weight": "134.0",
                "volume": "0.0",
                "status": "Cleared by Customs",
                "eventDate": "16SEP22",
                "eventTime": "18:58",
                "statusCode": "CCD"
            },
            {
                "@sequence": "7",
                "origin": "LHR",
                "dest": "MIA",
                "flightNum": "VS005",
                "flightCat": "P",
                "flightDate": "15SEP22",
                "arrivalDate": "15SEP22",
                "arrivalTime": "18:01",
                "numPieces": "1",
                "weight": "134.0",
                "volume": "0.0",
                "status": "Delivered",
                "eventDate": "16SEP22",
                "eventTime": "18:58",
                "statusCode": "DLV"
            }
        ]
    }
};